### ISSUE TITLE
Care to announce this on the FreeCAD forums?

### ISSUE THREAD

**Issue by luzpaz** [chbergmann/boxcreator#1]
Nice work. Here is the Users Showcase subforum: https://forum.freecadweb.org/viewforum.php?f=24 
Would you mind sharing your work on there? I'm sure the community would like it.

**Comment by luzpaz** [comment]
CC @probonopd
You may be interested in this macro

**Comment by chbergmann** [comment]
see https://forum.freecadweb.org/viewtopic.php?f=24&t=31795
