### ISSUE TITLE
Official FreeCAD macro repository

### ISSUE THREAD

**Issue by galou** [chbergmann/boxcreator#2]
Please consider adding your macro to the Official FreeCAD macro repository, https://github.com/FreeCAD/FreeCAD-macros/ to allow for it to be installable through the AddonManager.

One of the consequences would be that other people may touch your code.

**Comment by chbergmann** [comment]
I forked https://github.com/chbergmann/FreeCAD-macros
and added the scripts to the folder ObjectCreation
